<?php require 'templates/layout/header.phtml' ?>

<?php if ($genero->Ruta_Imagen <> null) : ?> <img src="<?= $genero->Ruta_Imagen ?>" alt=""> <?php endif ?>

<h1> <?= $genero->nombre ?> > </h1>
<a href="datosGenero/<?= $genero->id ?>" type="button" class='btn btn-success btn-sm ml-auto'>editar</a> 
<a href="eliminar/<?= $genero->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
 <ul class="list-group">
<?php foreach($libros as $libro): ?>
    <a href="listar/<?=$libro->id ?> "><li>   <?= $libro->titulo ?> </li></a>
<?php endforeach ?>

</ul>
<p class="mt-3"><small>Mostrando <?= $count ?> libros</small></p>


<?php require 'templates/layout/footer.phtml' ?>