<?php require 'templates/layout/header.phtml' ?>

<ul class="list-group">
<?php foreach($generos as $genero): ?>
    <a href="listar/<?=$genero->id ?> "><li> <?php if($genero->Ruta_Imagen <> null) : ?> <img src="<?= $genero->Ruta_Imagen ?>" alt="">  <?php endif ?>    <?= $genero->nombre ?>  > </li></a>
<?php endforeach ?>
</ul>
<p class="mt-3"><small>Mostrando <?=$count?> generos</small></p>


<?php require 'templates/layout/footer.phtml' ?>
